Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Max: 17
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - akasha.gemspec
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
