# Enables Travis to use their new container-based infrastructure
sudo: false

# Integration tests are using docker-compose
services:
  - docker

# Build for Ruby
language: ruby

# Enables caching for bundler
cache: bundler

# Passes arguments to bundle install (http://gembundler.com/man/bundle-install.1.html)
# bundler_args:

before_install:
  - gem update --system
  - gem update bundler

# Specify which ruby versions you wish to run your tests on, each version will be used
matrix:
  include:
    - rvm: 2.3.6
    - rvm: 2.5.1
    - env: INTEGRATION_TESTS=true

# Define how to run your tests.
script:
  - |
    # Run either integration tests or specs.
    case "$INTEGRATION_TESTS" in
      true) bin/integration-tests.sh ;;
      *) bundle exec rspec --tag ~integration ;;
    esac
  # Check if conventions are being followed.
  - bundle exec rake rubocop

# Disable email notifications
notifications:
 disabled: true
